#!/bin/bash
cat << 'EOF2' > patch.diff
--- js/UIScene.js
+++ js/UIScene.js
@@ -734,6 +734,7 @@
     openShowcase() { this.closeAllModals(); if (!this.nadagotchiData) return; const container = this.showcaseModal.passportContainer; container.removeAll(true); const width = 400; const height = 250; const cardBg = this.add.rectangle(0, 0, width, height, 0xFFF8E7).setStrokeStyle(4, 0xD4AF37); const frame = Config.MOOD_VISUALS.FRAMES[this.nadagotchiData.mood] ?? Config.MOOD_VISUALS.DEFAULT_FRAME; const sprite = this.add.image(-120, 0, 'pet', frame).setScale(8); const name = \`Archetype: \${this.nadagotchiData.dominantArchetype}\`; const gen = \`Generation: \${this.nadagotchiData.generation || 1}\`; const career = \`Career: \${this.nadagotchiData.currentCareer || 'Unemployed'}\`; const age = \`Age: \${Math.floor(this.nadagotchiData.age || 0)} Days\`; const infoText = this.add.text(0, -60, \`\${name}\\n\${gen}\\n\${career}\\n\${age}\`, { fontFamily: 'VT323, monospace', fontSize: '24px', color: '#000000', lineSpacing: 10 }).setOrigin(0, 0); const footer = this.add.text(0, 80, "OFFICIAL NADAGOTCHI PASSPORT", { fontFamily: 'Arial', fontSize: '12px', color: '#888888', fontStyle: 'italic' }).setOrigin(0.5); container.add([cardBg, sprite, infoText, footer]); this.showcaseModal.setVisible(true); this.scene.pause('MainScene'); }
     openCareerMenu() { this.closeAllModals(); if (!this.nadagotchiData) return; const container = this.careerModal; if (this.careerDynamicItems) { this.careerDynamicItems.forEach(i => i.destroy()); } this.careerDynamicItems = []; const mw = this.getModalWidth(); const mh = this.getModalHeight(); let yPos = -mh / 2 + 80; const career = this.nadagotchiData.currentCareer; let infoText = ""; if (career) { const level = this.nadagotchiData.careerLevels[career] || 1; const xp = this.nadagotchiData.careerXP[career] || 0; const title = CareerDefinitions.TITLES[career] ? CareerDefinitions.TITLES[career][level] : 'Employee'; const nextThreshold = CareerDefinitions.XP_THRESHOLDS[level + 1] || 'MAX'; const payBonus = (Config.CAREER.LEVEL_MULTIPLIERS[level] - 1) * 100; infoText = \`Current Job: \${career}\\nTitle: \${title} (Lvl \${level})\\nXP: \${xp} / \${nextThreshold}\\nBonuses: +\${Math.round(payBonus)}% Efficiency\`; } else { infoText = "No Active Career.\\nStudy or Explore to unlock paths!"; } const statsText = this.add.text(0, yPos, infoText, { fontFamily: 'VT323, monospace', fontSize: '24px', color: '#ffffff', align: 'center', wordWrap: { width: mw - 60 } }).setOrigin(0.5, 0); container.add(statsText); this.careerDynamicItems.push(statsText); yPos += 140; const listTitle = this.add.text(0, yPos, "Unlocked Career Paths:", { fontFamily: 'VT323', fontSize: '20px', color: '#AAAAAA' }).setOrigin(0.5); container.add(listTitle); this.careerDynamicItems.push(listTitle); yPos += 30; const unlocked = this.nadagotchiData.unlockedCareers || []; if (unlocked.length === 0) { const noneText = this.add.text(0, yPos, "(None yet)", { fontFamily: 'VT323', fontSize: '18px', color: '#888' }).setOrigin(0.5); container.add(noneText); this.careerDynamicItems.push(noneText); } else { unlocked.forEach(c => { const isCurrent = c === career; const lvl = this.nadagotchiData.careerLevels[c] || 1; const label = \`\${c} (Lvl \${lvl})\`; const rowText = this.add.text(-mw/2 + 60, yPos + 10, label, { fontFamily: 'VT323', fontSize: '24px', color: isCurrent ? '#00FF00' : '#FFF' }); container.add(rowText); this.careerDynamicItems.push(rowText); if (!isCurrent) { const switchBtn = ButtonFactory.createButton(this, (mw/2 - 80) + 40, (yPos + 20) + 15, "Switch", () => { this.game.events.emit(EventKeys.UI_ACTION, EventKeys.SWITCH_CAREER, c); container.setVisible(false); this.scene.resume('MainScene'); }, { width: 80, height: 30, color: 0x4CAF50, fontSize: '18px' }); container.add(switchBtn); this.careerDynamicItems.push(switchBtn); } else { const activeLbl = this.add.text(mw/2 - 80, yPos + 10, "[Active]", { fontFamily: 'VT323', fontSize: '18px', color: '#00FF00' }); container.add(activeLbl); this.careerDynamicItems.push(activeLbl); } yPos += 45; }); } container.setVisible(true); this.scene.pause('MainScene'); }
     openJobBoardMenu() { this.closeAllModals(); if (!this.nadagotchiData) return; const container = this.jobBoardModal; if (this.jobBoardDynamicItems) { this.jobBoardDynamicItems.forEach(i => i.destroy()); } this.jobBoardDynamicItems = []; const career = this.nadagotchiData.currentCareer; let text = ""; if (career) { text = \`Active Assignment:\\n\${career}\`; } else { text = "No Active Career Assignment."; } const infoText = this.add.text(0, -50, text, { fontFamily: 'VT323', fontSize: '32px', color: '#FFF', align: 'center' }).setOrigin(0.5); container.add(infoText); this.jobBoardDynamicItems.push(infoText); const startBtn = ButtonFactory.createButton(this, 80, 55, "Start Shift", () => { if (career) { this.game.events.emit(EventKeys.UI_ACTION, EventKeys.WORK); container.setVisible(false); } else { this.showToast("No Job", "Select a career first!", "🚫"); } }, { width: 160, height: 50, color: career ? 0x6A0DAD : 0x555555, fontSize: '24px' }); if (!career) startBtn.setDisabled(true); container.add(startBtn); this.jobBoardDynamicItems.push(startBtn); const careerBtn = ButtonFactory.createButton(this, 80, 120, "Career Profiles", () => { this.openCareerMenu(); }, { width: 160, height: 40, color: 0xD8A373, fontSize: '20px' }); container.add(careerBtn); this.jobBoardDynamicItems.push(careerBtn); container.setVisible(true); this.scene.pause('MainScene'); }
+    runTutorialSequence() {
     const steps = [
       {
         text: "These are your pet's STATS.\\nKeep an eye on Hunger and Energy!",
EOF2
patch -p0 < patch.diff
